<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Podcast_showsSeeder extends Seeder
{
    /**
     * Seed the podcast_shows table with the 6 existing shows.
     *
     * IDs are preserved from the original app to maintain foreign key
     * integrity with existing podcast_episodes records.
     *
     * user_id defaults to 1 for all records.
     */
    public function run(): void
    {
        DB::table('podcast_shows')->insert([
            [
                'id'                        => 2,
                'user_id'                   => 1,
                'title'                     => 'LaSalle Software News',
                'slug'                      => 'lasalle-software-news',
                'description'               => 'Lasalle Software News podcast talks about what is going on with the Laravel Framework based free and open source LaSalle Software. Hosted by Bob Bloom.',
                'rss_link'                  => 'https://pub-7874eb36e98742eab2d105f64e19e6ef.r2.dev/rss_lasalle_software_news.xml',
                'itunes_image'              => 'https://pub-0dfac1149b93421e9f5bae0107986f34.r2.dev/lasallesoftwarenews_logo_3000x3000.png',
                'itunes_language'           => 'en',
                'itunes_category_primary'   => 'Technology',
                'itunes_category_secondary' => null,
                'itunes_explicit'           => false,
                'itunes_author'             => 'Bob Bloom',
                'itunes_link'               => 'https://lasallesoftwarenews.com',
                'itunes_email'              => 'bob.bloom@lasallesoftware.ca',
                'itunes_name'               => 'Bob Bloom',
                'itunes_title'              => 'LaSalle Software News',
                'itunes_type'               => 'episodic',
                'itunes_copyright'          => 'Copyright © 2015 - 2026 South LaSalle Trading Corporation',
                'itunes_new_feed_url'       => null,
                'itunes_block'              => false,
                'itunes_complete'           => false,
                'itunes_summary'            => 'Lasalle Software News podcast talks about what is going on with the Laravel Framework based free and open source LaSalle Software. Hosted by Bob Bloom.',
                'itunes_subtitle'           => 'Lasalle Software News podcast talks about what is going on with the Laravel Framework based free and open source LaSalle Software. Hosted by Bob Bloom.',
                'itunes_content_encoded'    => null,
                'spotify_limit'             => 0,
                'spotify_country_of_origin' => 'global',
                'website_content'           => '<div>LaSalle Software is free open source software based on the Laravel Framework. It is an integrated web application, with a front-end and back-end. The apps are thin, with the source code residing in packages. Each package relates to a front or back end app. Features are encapsulated in individual packages. The UI\'s are in their own packages. I believe this is how Laravel apps should be built. LaSalle Software is integrated. A single back-end app supports multiple independent front-end apps. Only the back-end talks to the database. JWT for authentication. There is a blog. There is a profiles database. The back-end administration uses Laravel\'s Nova. Dusk tests go through the Nova forms. There is a custom guard for back-end user authentication. Laravel is used in its native way. No funny business. Third party packages install via composer as usual. This podcast answers these burning questions: What is happening with this project? What are the issues with Laravel? With Nova? What new projects are going on? Hosted by Bob Bloom.</div>',
                'website_excerpt'           => 'Lasalle Software News podcast talks about what is going on with the Laravel Framework based free and open source LaSalle Software. Hosted by Bob Bloom.',
                'website_meta_description'  => 'Lasalle Software News podcast talks about what is going on with the Laravel Framework based free and open source LaSalle Software. Hosted by Bob Bloom.',
                'website_featured_image'    => null,
                'website_publish_on'        => '2020-09-08',
                'website_enabled'           => true,
                'storage_artwork_url'       => 'https://pub-0dfac1149b93421e9f5bae0107986f34.r2.dev/',
                'storage_video_files_url'   => 'http://not-applicable.com',
                'storage_audio_files_url'   => 'https://pub-7c252511bd8c494f95403396af344af7.r2.dev/',
                'created_at'               => '2020-09-08 20:41:56',
                'updated_at'               => '2026-01-02 02:31:00',
            ],
            [
                'id'                        => 3,
                'user_id'                   => 1,
                'title'                     => 'The Bob Bloom Show',
                'slug'                      => 'bob-bloom-show',
                'description'               => 'The Bob Bloom Show is my monthly commentary podcast devoted to PHP, published on the first of the month. My main focus is pairing PHP with serverless platforms. Hosted by Bob Bloom.',
                'rss_link'                  => 'https://tbbs-rss.bobbloompodcasts.com/rss_bob_bloom_show.xml',
                'itunes_image'              => 'https://tbbs-images.bobbloompodcasts.com/bobbloomshow_logo_3000x3000.png',
                'itunes_language'           => 'en',
                'itunes_category_primary'   => 'Technology',
                'itunes_category_secondary' => null,
                'itunes_explicit'           => false,
                'itunes_author'             => 'Bob Bloom',
                'itunes_link'               => 'https://bobbloomshow.com',
                'itunes_email'              => 'bob.bloom@lasallesoftware.ca',
                'itunes_name'               => 'Bob Bloom',
                'itunes_title'              => 'The Bob Bloom Show',
                'itunes_type'               => 'episodic',
                'itunes_copyright'          => 'Copyright © 2010 - 2026 South LaSalle Trading Corporation',
                'itunes_new_feed_url'       => null,
                'itunes_block'              => false,
                'itunes_complete'           => false,
                'itunes_summary'            => 'The Bob Bloom Show is my monthly commentary podcast devoted to PHP, published on the first of the month. My main focus is pairing PHP with serverless platforms. Hosted by Bob Bloom.',
                'itunes_subtitle'           => 'The Bob Bloom Show is my monthly commentary podcast devoted to PHP, published on the first of the month. My main focus is pairing PHP with serverless platforms. Hosted by Bob Bloom.',
                'itunes_content_encoded'    => 'The Bob Bloom Show is my monthly commentary podcast devoted to PHP, published on the first of the month. My main focus is pairing PHP with serverless platforms. Hosted by Bob Bloom.',
                'spotify_limit'             => 0,
                'spotify_country_of_origin' => 'global',
                'website_content'           => '<div>The Bob Bloom Show is a commentary podcast devoted to PHP, with an emphasis on PHP serverless. Hosted by Bob Bloom.</div>',
                'website_excerpt'           => 'The Bob Bloom Show is a commentary podcast devoted to PHP, with an emphasis on PHP serverless. Hosted by Bob Bloom.',
                'website_meta_description'  => 'The Bob Bloom Show is a commentary podcast devoted to PHP, with an emphasis on PHP serverless. Hosted by Bob Bloom.',
                'website_featured_image'    => null,
                'website_publish_on'        => '2020-09-09',
                'website_enabled'           => true,
                'storage_artwork_url'       => 'https://tbbs-images.bobbloompodcasts.com/',
                'storage_video_files_url'   => 'https://not-applicable.com',
                'storage_audio_files_url'   => 'https://tbbs-audio.bobbloompodcasts.com/',
                'created_at'               => '2020-09-09 15:05:33',
                'updated_at'               => '2026-01-02 02:34:24',
            ],
            [
                'id'                        => 4,
                'user_id'                   => 1,
                'title'                     => 'The Bob Bloom Interviews',
                'slug'                      => 'bob-bloom-interviews-show',
                'description'               => 'Interviewing people about the PHP programming language. With a particular focus on pairing PHP with serverless. Hosted by Bob Bloom.',
                'rss_link'                  => 'https://tbbi-rss.bobbloompodcasts.com/rss_bob_bloom_interviews_show.xml',
                'itunes_image'              => 'https://tbbi-images.bobbloompodcasts.com/bobbloominterviews_logo_3000x3000.png',
                'itunes_language'           => 'en',
                'itunes_category_primary'   => 'Technology',
                'itunes_category_secondary' => null,
                'itunes_explicit'           => false,
                'itunes_author'             => 'Bob Bloom',
                'itunes_link'               => 'https://bobbloominterviews.com',
                'itunes_email'              => 'bob.bloom@lasallesoftware.ca',
                'itunes_name'               => 'Bob Bloom',
                'itunes_title'              => 'The Bob Bloom Interviews Show',
                'itunes_type'               => 'episodic',
                'itunes_copyright'          => 'Copyright © 2020 - 2026 South LaSalle Trading Corporation',
                'itunes_new_feed_url'       => null,
                'itunes_block'              => false,
                'itunes_complete'           => false,
                'itunes_summary'            => 'Interviewing people about the PHP programming language. With a particular focus on pairing PHP with serverless. Hosted by Bob Bloom.',
                'itunes_subtitle'           => 'Interviewing people about the PHP programming language. With a particular focus on pairing PHP with serverless. Hosted by Bob Bloom.',
                'itunes_content_encoded'    => 'Interviewing people about the PHP programming language. With a particular focus on pairing PHP with serverless. Hosted by Bob Bloom.',
                'spotify_limit'             => 0,
                'spotify_country_of_origin' => 'global',
                'website_content'           => '<div>The Bob Bloom Interviews is a podcast devoted to interviews about the PHP programming language. With a particular focus on pairing PHP with serverless.&nbsp;</div>',
                'website_excerpt'           => 'The Bob Bloom Interviews is a podcast devoted to interviews about the PHP programming language. With a particular focus on pairing PHP with serverless.',
                'website_meta_description'  => 'The Bob Bloom Interviews is a podcast devoted to interviews about the PHP programming language. With a particular focus on pairing PHP with serverless.',
                'website_featured_image'    => null,
                'website_publish_on'        => '2020-09-09',
                'website_enabled'           => true,
                'storage_artwork_url'       => 'https://tbbi-images.bobbloompodcasts.com/',
                'storage_video_files_url'   => 'http://not-applicable.com',
                'storage_audio_files_url'   => 'https://pub-1e0048dd19554436b851c142f5b7f550.r2.dev/',
                'created_at'               => '2020-09-09 15:08:16',
                'updated_at'               => '2026-01-02 02:34:02',
            ],
            [
                'id'                        => 10,
                'user_id'                   => 1,
                'title'                     => 'PHP Serverless News',
                'slug'                      => 'php-serverless-news',
                'description'               => 'Serverless news with a PHP point of view. With an eye on overall trends. Hosted by Bob Bloom.',
                'rss_link'                  => 'https://psn-rss.bobbloompodcasts.com/rss_php_serverless_news.xml',
                'itunes_image'              => 'https://psn-images.bobbloompodcasts.com/phpserverlessnews_logo_3000x3000.png',
                'itunes_language'           => 'en',
                'itunes_category_primary'   => 'Technology',
                'itunes_category_secondary' => null,
                'itunes_explicit'           => false,
                'itunes_author'             => 'Bob Bloom',
                'itunes_link'               => 'https://phpserverlessnews.com',
                'itunes_email'              => 'bob.bloom@lasallesoftware.ca',
                'itunes_name'               => 'Bob Bloom',
                'itunes_title'              => 'PHP Serverless News',
                'itunes_type'               => 'episodic',
                'itunes_copyright'          => 'Copyright © 2023 - 2026 South LaSalle Trading Corporation',
                'itunes_new_feed_url'       => null,
                'itunes_block'              => false,
                'itunes_complete'           => false,
                'itunes_summary'            => 'Serverless news with a PHP point of view. With an eye on overall trends. Hosted by Bob Bloom.',
                'itunes_subtitle'           => 'Serverless news with a PHP point of view. With an eye on overall trends. Hosted by Bob Bloom.',
                'itunes_content_encoded'    => 'Serverless news with a PHP point of view. With an eye on overall trends. Hosted by Bob Bloom.',
                'spotify_limit'             => 0,
                'spotify_country_of_origin' => 'global',
                'website_content'           => '<div>Serverless news with a PHP point of view. With an eye on overall trends. Hosted by Bob Bloom.</div>',
                'website_excerpt'           => 'Serverless news with a PHP point of view. With an eye on overall trends. Hosted by Bob Bloom.',
                'website_meta_description'  => 'Serverless news with a PHP point of view. With an eye on overall trends. Hosted by Bob Bloom.',
                'website_featured_image'    => null,
                'website_publish_on'        => '2023-01-01',
                'website_enabled'           => true,
                'storage_artwork_url'       => 'https://psn-images.bobbloompodcasts.com/',
                'storage_video_files_url'   => 'https://not-applicable.com',
                'storage_audio_files_url'   => 'https://psn-audio.bobbloompodcasts.com/',
                'created_at'               => '2023-02-11 15:03:35',
                'updated_at'               => '2026-01-02 02:33:08',
            ],
            [
                'id'                        => 11,
                'user_id'                   => 1,
                'title'                     => 'PHP Serverless Profiles',
                'slug'                      => 'php-serverless-profiles',
                'description'               => 'Serverless profiles with a PHP point of view. Hosted by Bob Bloom.',
                'rss_link'                  => 'https://psp-rss.bobbloompodcasts.com/rss_php_serverless_profiles.xml',
                'itunes_image'              => 'https://psp-images.bobbloompodcasts.com/phpserverlessprofiles_logo_3000x3000.png',
                'itunes_language'           => 'en',
                'itunes_category_primary'   => 'Technology',
                'itunes_category_secondary' => null,
                'itunes_explicit'           => false,
                'itunes_author'             => 'Bob Bloom',
                'itunes_link'               => 'https://phpserverlessprofiles.com',
                'itunes_email'              => 'bob.bloom@lasallesoftware.ca',
                'itunes_name'               => 'Bob Bloom',
                'itunes_title'              => 'PHP Serverless Profiles',
                'itunes_type'               => 'episodic',
                'itunes_copyright'          => 'Copyright © 2025 - 2026 South LaSalle Trading Corporation',
                'itunes_new_feed_url'       => null,
                'itunes_block'              => false,
                'itunes_complete'           => false,
                'itunes_summary'            => 'Serverless profiles with a PHP point of view. Hosted by Bob Bloom.',
                'itunes_subtitle'           => 'Serverless profiles with a PHP point of view. Hosted by Bob Bloom.',
                'itunes_content_encoded'    => 'Serverless profiles with a PHP point of view. Hosted by Bob Bloom.',
                'spotify_limit'             => 0,
                'spotify_country_of_origin' => 'global',
                'website_content'           => '<div>Serverless profiles with a PHP point of view. Hosted by Bob Bloom.</div>',
                'website_excerpt'           => 'Serverless profiles with a PHP point of view. Hosted by Bob Bloom.',
                'website_meta_description'  => 'Serverless profiles with a PHP point of view. Hosted by Bob Bloom.',
                'website_featured_image'    => null,
                'website_publish_on'        => '2025-02-01',
                'website_enabled'           => true,
                'storage_artwork_url'       => 'https://psp-images.bobbloompodcasts.com/',
                'storage_video_files_url'   => 'https://not-applicable.com',
                'storage_audio_files_url'   => 'https://psp-audio.bobbloompodcasts.com/',
                'created_at'               => '2025-02-16 16:13:42',
                'updated_at'               => '2026-01-02 02:32:26',
            ],
            [
                'id'                        => 12,
                'user_id'                   => 1,
                'title'                     => 'PHP Serverless Project Updates',
                'slug'                      => 'php-serverless-project-updates',
                'description'               => 'PHP Serverless Project Updates is my monthly podcast to update you about my PHP Serverless Project. Hosted by Bob Bloom.',
                'rss_link'                  => 'https://pspu-rss.bobbloompodcasts.com/rss_php_serverless_project_updates.xml',
                'itunes_image'              => 'https://pspu-images.bobbloompodcasts.com/phpserverlessprojectupdates_3000x3000.png',
                'itunes_language'           => 'en',
                'itunes_category_primary'   => 'Technology',
                'itunes_category_secondary' => null,
                'itunes_explicit'           => false,
                'itunes_author'             => 'Bob Bloom',
                'itunes_link'               => 'https://phpserverlessprojectupdates.com',
                'itunes_email'              => 'bob.bloom@lasallesoftware.ca',
                'itunes_name'               => 'Bob Bloom',
                'itunes_title'              => 'PHP Serverless Project Updates Podcast',
                'itunes_type'               => 'episodic',
                'itunes_copyright'          => 'Copyright © 2025 - 2026 South LaSalle Trading Corporation',
                'itunes_new_feed_url'       => null,
                'itunes_block'              => false,
                'itunes_complete'           => false,
                'itunes_summary'            => 'PHP Serverless Project Updates is my monthly podcast to update you about my PHP Serverless Project. Hosted by Bob Bloom.',
                'itunes_subtitle'           => 'PHP Serverless Project Updates is my monthly podcast to update you about my PHP Serverless Project. Hosted by Bob Bloom.',
                'itunes_content_encoded'    => 'PHP Serverless Project Updates is my monthly podcast to update you about my PHP Serverless Project. Hosted by Bob Bloom.',
                'spotify_limit'             => 0,
                'spotify_country_of_origin' => 'global',
                'website_content'           => '<div>PHP Serverless Project Updates is my monthly podcast to update you about my PHP Serverless Project. Hosted by Bob Bloom.</div>',
                'website_excerpt'           => 'PHP Serverless Project Updates is my monthly podcast to update you about my PHP Serverless Project. Hosted by Bob Bloom.',
                'website_meta_description'  => 'PHP Serverless Project Updates is my monthly podcast to update you about my PHP Serverless Project. Hosted by Bob Bloom.',
                'website_featured_image'    => null,
                'website_publish_on'        => '2025-07-19',
                'website_enabled'           => true,
                'storage_artwork_url'       => 'https://pspu-images.bobbloompodcasts.com/',
                'storage_video_files_url'   => 'https://not-applicable.com',
                'storage_audio_files_url'   => 'https://pspu-audio.bobbloompodcasts.com/',
                'created_at'               => '2025-07-20 15:08:08',
                'updated_at'               => '2026-01-02 02:31:49',
            ],
        ]);
    }
}