<?php

// =============================================================================
// GuestEmailMailable
//
// Sends an email to a podcast guest from @bobbloominterviews.com.
//
// Always sets a custom Message-ID so inbound replies can be correlated via
// Postmark's In-Reply-To header matching. The Message-ID is generated by
// GuestEmailService before construction — the caller stores it in guest_emails.
//
// When $inReplyTo is provided (replying within an existing thread), sets
// In-Reply-To and References headers so the guest's email client groups the
// conversation as a single thread rather than separate messages.
//
// Named GuestEmailMailable (not GuestEmail) to avoid collision with the
// GuestEmail model in the same Guests feature folder.
//
// Path: MEDIA_PLATFORM/Podcasts/Guests/Mail/
// =============================================================================

namespace MediaPlatform\Podcasts\Guests\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Mail\Mailables\Headers;
use Illuminate\Queue\SerializesModels;
use MediaPlatform\Podcasts\Guests\Models\PodcastGuest;

class GuestEmailMailable extends Mailable
{
    use Queueable, SerializesModels;

    /**
     * @param PodcastGuest $guest     The recipient guest.
     * @param string       $subject   Email subject line.
     * @param string       $body      Email body text (plain text; rendered via nl2br in the view).
     * @param string       $messageId Pre-generated Message-ID without angle brackets.
     * @param string|null  $inReplyTo Message-ID of the prior email in this thread, without angle brackets.
     */
    public function __construct(
        public PodcastGuest  $guest,
        private string       $emailSubject,
        public string        $body,
        private string       $messageId,
        private ?string      $inReplyTo = null,
    ) {}

    /**
     * Define the email envelope — subject only.
     * Recipient is set by the caller via Mail::to().
     */
    public function envelope(): Envelope
    {
        return new Envelope(
            subject: $this->emailSubject,
        );
    }

    /**
     * Define the email body template.
     * $guest and $body are public properties and are automatically available in the view.
     */
    public function content(): Content
    {
        return new Content(
            view: 'media_platform.podcasts.guests.mail.guest_email',
        );
    }

    /**
     * Set RFC 2822 threading headers.
     *
     * Message-ID is always set so inbound replies can be correlated.
     * In-Reply-To and References are set when replying to a prior message,
     * keeping the conversation grouped as a thread in the guest's email client.
     *
     * messageId and references values are passed without angle brackets —
     * Laravel's Headers class adds them when building the headers.
     * In-Reply-To is set via the text array as a raw header, so angle brackets
     * are added manually here.
     */
    public function headers(): Headers
    {
        $text = [];

        if ($this->inReplyTo) {
            $text['In-Reply-To'] = '<' . $this->inReplyTo . '>';
        }

        return new Headers(
            messageId:  $this->messageId,
            references: $this->inReplyTo ? [$this->inReplyTo] : [],
            text:       $text,
        );
    }
}